name = "album-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "album-db"
database_id = "a901e4bc-ea2d-4e45-b25e-e161b93e30d1"

[vars]
ALLOWED_ORIGINS = "*"
FIREBASE_PROJECT_ID = "myott-a40db"
ALLOWED_ADMIN_EMAILS = "usestoreme@gmail.com"
