kind = "web"
previewPath = "/"
title = "Album"
version = "1.0.0"
id = "artifacts/public-site"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20918

[services.development]
run = "pnpm --filter @workspace/public-site run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/public-site", "run", "build" ]
publicDir = "artifacts/public-site/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20918"
BASE_PATH = "/"
